version: "2"
services:
  webserver:
    image: supraimage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: supraelectronics.sql
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      SITE_URL: http://localhost
    networks:
      - test

networks:
  test:
    external: true